name: Test

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: "Install uv (py-${{ matrix.python-version }})"
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.17"
        python-version: ${{ matrix.python-version }}
        activate-environment: true
    - name: Install dependencies
      run: |
        uv sync --group test
    - name: Run tests (py-${{ matrix.python-version }})
      run: |
        uv run --frozen pytest -q
